Create project
valra/Photons pull request #3
Opened 2019-02-04 01:58 UTC by siddarthkalra

2019-02-05 02:35 UTC, vastopa requested changes

2019-02-05 02:35 UTC, vastopa commented on Photons.xcodeproj/xcuserdata/skalra.xcuserdatad/xcschemes/xcschememanagement.plist
> +<?xml version="1.0" encoding="UTF-8"?>
This branch needs to be backmerged with `master` to remove `Photons.xcodeproj/xcuserdata/*` files

2019-02-05 02:35 UTC, vastopa commented on Photons.xcodeproj/project.xcworkspace/contents.xcworkspacedata
> +<?xml version="1.0" encoding="UTF-8"?>
I believe we want to also include `project.xcworkspace` in our `.gitignore` 

If you agree with this and will be adding it, might as well add `.DS_Store` while you're at it 🙃

2019-02-06 03:29 UTC, siddarthkalra commented on Photons.xcodeproj/xcuserdata/skalra.xcuserdatad/xcschemes/xcschememanagement.plist
> +<?xml version="1.0" encoding="UTF-8"?>
This is done: https://github.com/valra/Photons/pull/3/commits/45c47fbe033cee6bcfbcd07a1ecbca1d30239639

2019-02-06 03:30 UTC, siddarthkalra commented on Photons.xcodeproj/project.xcworkspace/contents.xcworkspacedata
> +<?xml version="1.0" encoding="UTF-8"?>
I've normally not done that because it does have a shared component. Although, it has a `xcuserdata` subdir which can be excluded. This is done here: https://github.com/valra/Photons/pull/3/commits/45c47fbe033cee6bcfbcd07a1ecbca1d30239639 and here: https://github.com/valra/Photons/pull/3/commits/6cb5d637b805b8b21dae61b7e1f0a868cc7f0a9d.

2019-02-06 03:39 UTC, vastopa approved these changes

2019-02-06 03:39 UTC, merged